### ISSUE TITLE
Script Error Log

### ISSUE THREAD

**Issue by mfekry** [SpeedySQL/HealthCheck#2]
when i ran the script against DB i got the following error
Error:WaitStats.sql - Retrieving the COM class factory for component with CLSID {00000000-0000-0000-0000-000000000000} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).

please advice

**Comment by SpeedySQL** [comment]
Hi, 
The error suggests that Excel is not installed.  Could you please verify that Excel is installed on the machine from where you are running the health check?
Omid

**Comment by SpeedySQL** [comment]
Hi, 
The error suggests that Excel is not installed.  Could you please verify that Excel is installed on the machine from where you are running the health check?
Omid

**Comment by mfekry** [comment]
thanks Man for your support , the excel was corrupted so i reinstalled it & it works fine
